# GitHub Defaults
highlighter: true
safe: true

# UTF-8 & parse errors fix
#markdown: redcarpet
#extensions: ["fenced_code_blocks", "no_intra_emphasis", "superscript", "strikethrough", "autolink"]

markdown: kramdown
kramdown:
  input: GFM
